---
- name: install nginx web server
  hosts: nginx
  become: yes
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Ensure nginx package 
      ansible.builtin.apt:
        name: nginx
        state: present
